
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  run:
    path: "main.go"
    extra: ""
    watchPaths:
      - "internal"
      - "api"

  gen:
    dao:
      - link: "mysql:root:gbaseadmin123@tcp(127.0.0.1:3306)/gbaseadmin?charset=utf8mb4"
        tables: "dept,role,role_dept,role_menu,menu,users,user_dept,user_role"
        descriptionTag: true
        noJsonTag: true
        noModelComment: false
        overwriteDao: false
        modelFile: ""
        tplDaoIndexPath: ""
        tplDaoInternalPath: ""

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app