// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// roleDeptDao is the data access object for the table system_role_dept.
// You can define custom methods on it to extend its functionality as needed.
type roleDeptDao struct {
	*internal.RoleDeptDao
}

var (
	// RoleDept is a globally accessible object for table system_role_dept operations.
	RoleDept = roleDeptDao{internal.NewRoleDeptDao()}
)

// Add your custom methods and functionality below.
