// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// userDeptDao is the data access object for the table user_dept.
// You can define custom methods on it to extend its functionality as needed.
type userDeptDao struct {
	*internal.UserDeptDao
}

var (
	// UserDept is a globally accessible object for table user_dept operations.
	UserDept = userDeptDao{internal.NewUserDeptDao()}
)

// Add your custom methods and functionality below.
