// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// userDeptDao is the data access object for the table system_user_dept.
// You can define custom methods on it to extend its functionality as needed.
type userDeptDao struct {
	*internal.UserDeptDao
}

var (
	// UserDept is a globally accessible object for table system_user_dept operations.
	UserDept = userDeptDao{internal.NewUserDeptDao()}
)

// 注意：当前未使用，预留给用户-部门多对多关联功能。
// 当需要支持一个用户同时归属多个部门时，可通过此 DAO 操作 user_dept 关联表。
