gfcli:
  gen:
    dao:
      - link: "mysql:root:gbaseadmin123@tcp(127.0.0.1:3306)/gbaseadmin?charset=utf8mb4"
        tables: "dept,role,menu,users,role_dept,role_menu,user_role,user_dept"
        descriptionTag: true
        noModelComment: false
        jsonCase: "CamelLower"
        gJsonSupport: true
        overwriteDao: false
        modelFile: "entity"
        tplDaoIndexPath: ""
        tplDaoInternalPath: ""
        path: "./app/system"

    service:
      - srcFolder: "./app/system/internal/logic"
        dstFolder: "./app/system/internal/service"
        watchFile: ""
        packages: ""
