
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  run:
    path: "main.go"
    extra: ""
    watchPaths:
      - "internal"
      - "api"

  gen:
    dao:
      - link: "mysql:root:gbaseadmin123@tcp(127.0.0.1:3306)/gbaseadmin?charset=utf8mb4"
        tables: "play_activity,play_activity_join,play_activity_reward,play_activity_step,play_activity_step_log,play_balance_log,play_category,play_coach,play_coach_apply,play_coach_level,play_coupon,play_coupon_member,play_goods,play_member,play_member_level,play_oauth,play_order,play_payment,play_profit_log,play_recharge_order,play_recharge_plan,play_review,play_shop"
        descriptionTag: true
        noJsonTag: true
        noModelComment: false
        overwriteDao: false

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
