// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/upload/internal/dao/internal"
)

// uploadDirRuleDao is the data access object for the table upload_dir_rule.
// You can define custom methods on it to extend its functionality as needed.
type uploadDirRuleDao struct {
	*internal.UploadDirRuleDao
}

var (
	// UploadDirRule is a globally accessible object for table upload_dir_rule operations.
	UploadDirRule = uploadDirRuleDao{internal.NewUploadDirRuleDao()}
)

// Add your custom methods and functionality below.
