// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/upload/internal/dao/internal"
)

// uploadConfigDao is the data access object for the table upload_config.
// You can define custom methods on it to extend its functionality as needed.
type uploadConfigDao struct {
	*internal.UploadConfigDao
}

var (
	// UploadConfig is a globally accessible object for table upload_config operations.
	UploadConfig = uploadConfigDao{internal.NewUploadConfigDao()}
)

// Add your custom methods and functionality below.
