// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/upload/internal/dao/internal"
)

// uploadDirDao is the data access object for the table upload_dir.
// You can define custom methods on it to extend its functionality as needed.
type uploadDirDao struct {
	*internal.UploadDirDao
}

var (
	// UploadDir is a globally accessible object for table upload_dir operations.
	UploadDir = uploadDirDao{internal.NewUploadDirDao()}
)

// Add your custom methods and functionality below.
