// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playCoachApplyDao is the data access object for the table play_coach_apply.
// You can define custom methods on it to extend its functionality as needed.
type playCoachApplyDao struct {
	*internal.PlayCoachApplyDao
}

var (
	// PlayCoachApply is a globally accessible object for table play_coach_apply operations.
	PlayCoachApply = playCoachApplyDao{internal.NewPlayCoachApplyDao()}
)

// Add your custom methods and functionality below.
