// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playProfitLogDao is the data access object for the table play_profit_log.
// You can define custom methods on it to extend its functionality as needed.
type playProfitLogDao struct {
	*internal.PlayProfitLogDao
}

var (
	// PlayProfitLog is a globally accessible object for table play_profit_log operations.
	PlayProfitLog = playProfitLogDao{internal.NewPlayProfitLogDao()}
)

// Add your custom methods and functionality below.
