// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playWithdrawDao is the data access object for the table play_withdraw.
// You can define custom methods on it to extend its functionality as needed.
type playWithdrawDao struct {
	*internal.PlayWithdrawDao
}

var (
	// PlayWithdraw is a globally accessible object for table play_withdraw operations.
	PlayWithdraw = playWithdrawDao{internal.NewPlayWithdrawDao()}
)

// Add your custom methods and functionality below.
