// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playCategoryDao is the data access object for the table play_category.
// You can define custom methods on it to extend its functionality as needed.
type playCategoryDao struct {
	*internal.PlayCategoryDao
}

var (
	// PlayCategory is a globally accessible object for table play_category operations.
	PlayCategory = playCategoryDao{internal.NewPlayCategoryDao()}
)

// Add your custom methods and functionality below.
