// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playPaymentDao is the data access object for the table play_payment.
// You can define custom methods on it to extend its functionality as needed.
type playPaymentDao struct {
	*internal.PlayPaymentDao
}

var (
	// PlayPayment is a globally accessible object for table play_payment operations.
	PlayPayment = playPaymentDao{internal.NewPlayPaymentDao()}
)

// Add your custom methods and functionality below.
