// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playMessageDao is the data access object for the table play_message.
// You can define custom methods on it to extend its functionality as needed.
type playMessageDao struct {
	*internal.PlayMessageDao
}

var (
	// PlayMessage is a globally accessible object for table play_message operations.
	PlayMessage = playMessageDao{internal.NewPlayMessageDao()}
)

// Add your custom methods and functionality below.
