// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playActivityJoinDao is the data access object for the table play_activity_join.
// You can define custom methods on it to extend its functionality as needed.
type playActivityJoinDao struct {
	*internal.PlayActivityJoinDao
}

var (
	// PlayActivityJoin is a globally accessible object for table play_activity_join operations.
	PlayActivityJoin = playActivityJoinDao{internal.NewPlayActivityJoinDao()}
)

// Add your custom methods and functionality below.
