// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playBannerDao is the data access object for the table play_banner.
// You can define custom methods on it to extend its functionality as needed.
type playBannerDao struct {
	*internal.PlayBannerDao
}

var (
	// PlayBanner is a globally accessible object for table play_banner operations.
	PlayBanner = playBannerDao{internal.NewPlayBannerDao()}
)

// Add your custom methods and functionality below.
