// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playGoodsDao is the data access object for the table play_goods.
// You can define custom methods on it to extend its functionality as needed.
type playGoodsDao struct {
	*internal.PlayGoodsDao
}

var (
	// PlayGoods is a globally accessible object for table play_goods operations.
	PlayGoods = playGoodsDao{internal.NewPlayGoodsDao()}
)

// Add your custom methods and functionality below.
