// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playBalanceLogDao is the data access object for the table play_balance_log.
// You can define custom methods on it to extend its functionality as needed.
type playBalanceLogDao struct {
	*internal.PlayBalanceLogDao
}

var (
	// PlayBalanceLog is a globally accessible object for table play_balance_log operations.
	PlayBalanceLog = playBalanceLogDao{internal.NewPlayBalanceLogDao()}
)

// Add your custom methods and functionality below.
