// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playActivityDao is the data access object for the table play_activity.
// You can define custom methods on it to extend its functionality as needed.
type playActivityDao struct {
	*internal.PlayActivityDao
}

var (
	// PlayActivity is a globally accessible object for table play_activity operations.
	PlayActivity = playActivityDao{internal.NewPlayActivityDao()}
)

// Add your custom methods and functionality below.
