// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playActivityStepDao is the data access object for the table play_activity_step.
// You can define custom methods on it to extend its functionality as needed.
type playActivityStepDao struct {
	*internal.PlayActivityStepDao
}

var (
	// PlayActivityStep is a globally accessible object for table play_activity_step operations.
	PlayActivityStep = playActivityStepDao{internal.NewPlayActivityStepDao()}
)

// Add your custom methods and functionality below.
