// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playShopDao is the data access object for the table play_shop.
// You can define custom methods on it to extend its functionality as needed.
type playShopDao struct {
	*internal.PlayShopDao
}

var (
	// PlayShop is a globally accessible object for table play_shop operations.
	PlayShop = playShopDao{internal.NewPlayShopDao()}
)

// Add your custom methods and functionality below.
