// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playOauthDao is the data access object for the table play_oauth.
// You can define custom methods on it to extend its functionality as needed.
type playOauthDao struct {
	*internal.PlayOauthDao
}

var (
	// PlayOauth is a globally accessible object for table play_oauth operations.
	PlayOauth = playOauthDao{internal.NewPlayOauthDao()}
)

// Add your custom methods and functionality below.
