// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playMemberLevelDao is the data access object for the table play_member_level.
// You can define custom methods on it to extend its functionality as needed.
type playMemberLevelDao struct {
	*internal.PlayMemberLevelDao
}

var (
	// PlayMemberLevel is a globally accessible object for table play_member_level operations.
	PlayMemberLevel = playMemberLevelDao{internal.NewPlayMemberLevelDao()}
)

// Add your custom methods and functionality below.
