// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playRechargeOrderDao is the data access object for the table play_recharge_order.
// You can define custom methods on it to extend its functionality as needed.
type playRechargeOrderDao struct {
	*internal.PlayRechargeOrderDao
}

var (
	// PlayRechargeOrder is a globally accessible object for table play_recharge_order operations.
	PlayRechargeOrder = playRechargeOrderDao{internal.NewPlayRechargeOrderDao()}
)

// Add your custom methods and functionality below.
