// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playRechargePlanDao is the data access object for the table play_recharge_plan.
// You can define custom methods on it to extend its functionality as needed.
type playRechargePlanDao struct {
	*internal.PlayRechargePlanDao
}

var (
	// PlayRechargePlan is a globally accessible object for table play_recharge_plan operations.
	PlayRechargePlan = playRechargePlanDao{internal.NewPlayRechargePlanDao()}
)

// Add your custom methods and functionality below.
