// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playActivityStepLogDao is the data access object for the table play_activity_step_log.
// You can define custom methods on it to extend its functionality as needed.
type playActivityStepLogDao struct {
	*internal.PlayActivityStepLogDao
}

var (
	// PlayActivityStepLog is a globally accessible object for table play_activity_step_log operations.
	PlayActivityStepLog = playActivityStepLogDao{internal.NewPlayActivityStepLogDao()}
)

// Add your custom methods and functionality below.
