// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playCoachDao is the data access object for the table play_coach.
// You can define custom methods on it to extend its functionality as needed.
type playCoachDao struct {
	*internal.PlayCoachDao
}

var (
	// PlayCoach is a globally accessible object for table play_coach operations.
	PlayCoach = playCoachDao{internal.NewPlayCoachDao()}
)

// Add your custom methods and functionality below.
