// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playActivityRewardDao is the data access object for the table play_activity_reward.
// You can define custom methods on it to extend its functionality as needed.
type playActivityRewardDao struct {
	*internal.PlayActivityRewardDao
}

var (
	// PlayActivityReward is a globally accessible object for table play_activity_reward operations.
	PlayActivityReward = playActivityRewardDao{internal.NewPlayActivityRewardDao()}
)

// Add your custom methods and functionality below.
