// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playReviewDao is the data access object for the table play_review.
// You can define custom methods on it to extend its functionality as needed.
type playReviewDao struct {
	*internal.PlayReviewDao
}

var (
	// PlayReview is a globally accessible object for table play_review operations.
	PlayReview = playReviewDao{internal.NewPlayReviewDao()}
)

// Add your custom methods and functionality below.
