// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playCouponMemberDao is the data access object for the table play_coupon_member.
// You can define custom methods on it to extend its functionality as needed.
type playCouponMemberDao struct {
	*internal.PlayCouponMemberDao
}

var (
	// PlayCouponMember is a globally accessible object for table play_coupon_member operations.
	PlayCouponMember = playCouponMemberDao{internal.NewPlayCouponMemberDao()}
)

// Add your custom methods and functionality below.
