// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playMemberDao is the data access object for the table play_member.
// You can define custom methods on it to extend its functionality as needed.
type playMemberDao struct {
	*internal.PlayMemberDao
}

var (
	// PlayMember is a globally accessible object for table play_member operations.
	PlayMember = playMemberDao{internal.NewPlayMemberDao()}
)

// Add your custom methods and functionality below.
