// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playOrderDao is the data access object for the table play_order.
// You can define custom methods on it to extend its functionality as needed.
type playOrderDao struct {
	*internal.PlayOrderDao
}

var (
	// PlayOrder is a globally accessible object for table play_order operations.
	PlayOrder = playOrderDao{internal.NewPlayOrderDao()}
)

// Add your custom methods and functionality below.
