// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/play/internal/dao/internal"
)

// playCoachLevelDao is the data access object for the table play_coach_level.
// You can define custom methods on it to extend its functionality as needed.
type playCoachLevelDao struct {
	*internal.PlayCoachLevelDao
}

var (
	// PlayCoachLevel is a globally accessible object for table play_coach_level operations.
	PlayCoachLevel = playCoachLevelDao{internal.NewPlayCoachLevelDao()}
)

// Add your custom methods and functionality below.
