export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/category/index',
    'pages/activity/list',
    'pages/message/index',
    'pages/mine/index',
    'pages/search/index',
    'pages/coach/list',
    'pages/coach/detail',
    'pages/coach/apply',
    'pages/coach/apply-status',
    'pages/goods/detail',
    'pages/order/confirm',
    'pages/order/list',
    'pages/order/detail',
    'pages/order/pay',
    'pages/order/review',
    'pages/recharge/index',
    'pages/coupon/list',
    'pages/coupon/center',
    'pages/activity/detail',
    'pages/mine/profile',
    'pages/mine/balance',
    'pages/mine/settings',
    'pages/login/index',
    'pages/workspace/index',
    'pages/workspace/orders',
    'pages/workspace/income',
    'pages/workspace/goods',
    'pages/workspace/reviews',
    'pages/webview/index',
  ],
  tabBar: {
    color: '#B2BEC3',
    selectedColor: '#6C5CE7',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/index/index', text: '首页', iconPath: 'assets/tab/home.png', selectedIconPath: 'assets/tab/home-active.png' },
      { pagePath: 'pages/category/index', text: '分类', iconPath: 'assets/tab/category.png', selectedIconPath: 'assets/tab/category-active.png' },
      { pagePath: 'pages/activity/list', text: '活动', iconPath: 'assets/tab/gift.png', selectedIconPath: 'assets/tab/gift-active.png' },
      { pagePath: 'pages/message/index', text: '消息', iconPath: 'assets/tab/message.png', selectedIconPath: 'assets/tab/message-active.png' },
      { pagePath: 'pages/mine/index', text: '我的', iconPath: 'assets/tab/user.png', selectedIconPath: 'assets/tab/user-active.png' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '陪玩平台',
    navigationBarTextStyle: 'black',
  },
});
