
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  run:
    path: "main.go"
    extra: ""
    watchPaths:
      - "internal"
      - "api"

  gen:
    dao:
      - link: "mysql:root:gbaseadmin123@tcp(127.0.0.1:3306)/gbaseadmin?charset=utf8mb4"
        tables: "upload_config,upload_dir,upload_dir_rule,upload_file"
        descriptionTag: true
        noJsonTag: true
        noModelComment: false
        overwriteDao: false

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
